// Mock data for job search page
export const mockJobSearchData = {
  totalJobs: 2150,
  jobs: [
    {
      id: 1,
      title: "Senior Web Designer",
      company: "Company",
      location: "1363-1385 Sunset Blvd Los Angeles, CA 90026, USA",
      salary: "$2500",
      period: "Month",
      type: "New",
      typeColor: "bg-green-500",
      posted: "1 days ago",
      logo: "https://thewebmax.org/react/jobzilla/assets/images/jobs-company/pic2.jpg",
    },
    {
      id: 2,
      title: "Sr. Rolling Stock Technician",
      company: "Business",
      location: "1363-1385 Sunset Blvd Los Angeles, CA 90026, USA",
      salary: "$2500",
      period: "Month",
      type: "Internship",
      typeColor: "bg-orange-500",
      posted: "15 days ago",
      logo: "https://thewebmax.org/react/jobzilla/assets/images/jobs-company/pic4.jpg",
    },
    {
      id: 3,
      title: "IT Department Manager",
      company: "Company Name",
      location: "1363-1385 Sunset Blvd Los Angeles, CA 90026, USA",
      salary: "$2500",
      period: "Month",
      type: "Full-time",
      typeColor: "bg-purple-500",
      posted: "6 months ago",
      logo: "https://thewebmax.org/react/jobzilla/assets/images/jobs-company/pic2.jpg",
    },
    {
      id: 4,
      title: "Art Production Specialist",
      company: "Arrow",
      location: "1363-1385 Sunset Blvd Los Angeles, CA 90026, USA",
      salary: "$1500",
      period: "Month",
      type: "Freelancer",
      typeColor: "bg-cyan-500",
      posted: "2 days ago",
      logo: "https://thewebmax.org/react/jobzilla/assets/images/jobs-company/pic2.jpg",
    },
    {
      id: 5,
      title: "Recreation & Fitness Worker",
      company: "Vector Logo",
      location: "1363-1385 Sunset Blvd Los Angeles, CA 90026, USA",
      salary: "$800",
      period: "Month",
      type: "Temporary",
      typeColor: "bg-yellow-600",
      posted: "1 days ago",
      logo: "https://thewebmax.org/react/jobzilla/assets/images/jobs-company/pic4.jpg",
    },
  ],
  industries: [
    "Security / Protection",
    "Occupational Safety",
    "Sales / Business",
    "Retail / Wholesale",
    "Media / Publishing",
    "Insurance",
    "Maintenance / Repair",
    "Information Technology",
    "Education / Training",
    "Healthcare",
  ],
  levels: ["Intern", "Entry Level", "Staff", "Manager", "Director"],
  experiences: [
    "Under 1 year",
    "1 - 2 years",
    "2 - 5 years",
    "5 - 10 years",
    "Over 10 years",
  ],
  educations: [
    "High School",
    "Vocational",
    "College",
    "Bachelor",
    "Master",
    "PhD",
  ],
  jobTypes: ["Full-time", "Part-time", "Internship", "Freelance", "Contract"],
  datePosted: [
    "Today",
    "Last 3 days",
    "Last week",
    "Last 2 weeks",
    "Last month",
  ],
  suggestedJobs: [
    {
      id: 101,
      title: "Frontend Developer",
      company: "TechCorp",
      salary: "$3000",
      type: "Remote",
      typeColor: "bg-blue-500",
    },
    {
      id: 102,
      title: "UX Designer",
      company: "DesignStudio",
      salary: "$2800",
      type: "Hybrid",
      typeColor: "bg-green-500",
    },
    {
      id: 103,
      title: "Product Manager",
      company: "StartupXYZ",
      salary: "$4000",
      type: "On-site",
      typeColor: "bg-purple-500",
    },
    {
      id: 104,
      title: "Data Analyst",
      company: "DataCorp",
      salary: "$2200",
      type: "Remote",
      typeColor: "bg-orange-500",
    },
  ],
};

// String formatters for currency and experience
export const formatSalary = (amount: number): string => {
  return `${amount} million VND`;
};

export const formatExperience = (years: string): string => {
  return years;
};
