// Mock data for job detail page
export const mockJobDetailData = {
  job: {
    id: 1,
    title: "Senior Web Designer, Developer",
    company: "Company",
    companySize: "25 - 99 nhân viên",
    companyContact: "Công ty TNHH Phong Thạnh",
    logo: "https://static.vecteezy.com/system/resources/previews/047/656/219/non_2x/abstract-logo-design-for-any-corporate-brand-business-company-vector.jpg",
    coverImage:
      "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=400&fit=crop",
    location: "Thành Phố Thuận An, Bình Dương",
    address:
      "Thửa đất số 253, tổ bản đồ số E1, Đại Lộ Bình Dương, KP Bình Giao, P THuận Giao, Thành Phố Thuận An, Bình Dương, Viet Nam",
    salary: "$2000 - $2500",
    period: "Month",
    experience: "1 - 2 năm kinh nghiệm",
    level: "Nhân viên toàn thời gian",
    jobType: "Bán hàng / Kinh doanh",
    education: "Cử nhân",
    gender: "Bất kỳ",
    posted: "1 days ago",
    deadline: "October 1, 2025",
    applicationDeadline: "28-08-2025",
    remainingDays: "2 Ngày tới",
    isNew: true,
    featured: true,
    website: "https://thewebmax.com",
    language: "Tiếng Việt",
  },
  jobDescription: {
    keyResponsibilities: [
      "Prepare, check, and process quotations, proforma invoices, purchase orders, and contracts.",
      "Maintain accurate sales records, databases, and customer information.",
      "Coordinate with logistics, production, and finance teams to ensure smooth order processing and delivery.",
      "Track sales orders, shipments, and payments; follow up with customers when necessary.",
      "Support the sales team with administrative tasks such as scheduling meetings, preparing presentations, and handling correspondence.",
      "Prepare sales reports and performance analysis for management.",
      "Handle inquiries and maintain positive customer relationships through professional communication.",
    ],
    whatWeOffer: [
      "Competitive salary, 13th-month bonus, and full social insurance benefits.",
      "Professional and supportive working environment.",
      "Opportunities for career growth and training.",
      "Benefits according to company policy.",
    ],
    vietnameseResponsibilities: [
      "Chuẩn bị, kiểm tra và xử lý báo giá, hóa đơn chiều lẻ, đơn đặt hàng và hợp đồng.",
      "Quản lý và cập nhật chính xác hồ sơ bán hàng, cơ sở dữ liệu và thông tin khách hàng.",
      "Phối hợp với bộ phận logistics, sản xuất và tài chính để đảm bảo đơn hàng được xử lý và giao đúng tiến độ.",
      "Theo dõi đơn hàng, giao hàng và thanh toán; chủ động nhắc nhở khách hàng khi cần thiết.",
      "Hỗ trợ đội ngũ kinh doanh trong các công việc hành chính như sắp xếp lịch họp, chuẩn bị tài liệu, và xử lý thư từ.",
      "Chuẩn bị báo cáo bán hàng và phân tích hiệu suất cho ban quản lý.",
    ],
    benefits: [
      "Mức lương cạnh tranh, thưởng lương tháng 13, BHXH đầy đủ.",
      "Môi trường làm việc chuyên nghiệp, thân thiện và hỗ trợ.",
      "Cơ hội phát triển nghề nghiệp.",
      "Các chế độ phúc lợi theo chính sách công ty.",
    ],
  },
  qualifications: {
    english: [
      "Bachelor's degree in Business Administration, Marketing, or related field.",
      "Experience in sales administration, sales support, or customer service is an advantage.",
      "Strong organizational skills with attention to detail.",
      "Good communication and interpersonal skills.",
      "Proficient in MS Office; experience with ERP/CRM systems is a plus.",
      "Ability to multitask and work under deadlines.",
      "Team player with problem-solving skills.",
    ],
    vietnamese: [
      "Tốt nghiệp đại học chuyên ngành Quản trị Kinh doanh, Marketing hoặc các ngành liên quan.",
      "Có kinh nghiệm trong hành chính kinh doanh, hỗ trợ bán hàng hoặc chăm sóc khách hàng là một lợi thế.",
      "Kỹ năng tổ chức công việc tốt, chú ý đến chi tiết.",
      "Kỹ năng giao tiếp và quan hệ cá nhân tốt.",
      "Thành thạo tin học văn phòng (MS Office); biết sử dụng hệ thống ERP/CRM là một lợi thế.",
      "Có khả năng làm nhiều việc cùng lúc và làm việc dưới áp lực thời hạn.",
      "Có tinh thần làm việc nhóm và kỹ năng giải quyết vấn đề.",
    ],
  },
  companyInfo: {
    name: "Công ty TNHH Phong Thạnh",
    size: "25 - 99 nhân viên",
    contact: "Công ty TNHH Phong Thạnh",
    description:
      "Công ty TNHH Phong Thạnh là một trong những đơn vị sản xuất và xuất khẩu uy tín tại Việt Nam trong lĩnh vực chất đất nung, gốm sứ trang trí và sản phẩm nội ngoại thất xuất khẩu đi các nước trên thế giới. Với nhiều năm kinh nghiệm, chúng tôi luôn cam kết mang đến cho khách hàng trên toàn thế giới những sản phẩm chất lượng cao, thân thiện với môi trường và dịch vụ chuyên nghiệp.",
    applicationInstructions: [
      "Please send your application by online, mail or direct to company.",
      "Các ứng viên quan tâm vui lòng gửi hồ sơ trực tuyến qua hệ thống CareerLink, gửi kèm file hoặc trực tiếp đến tại công ty.",
    ],
  },
  relatedJobs: [
    {
      id: 2,
      title: "Frontend Developer",
      company: "TechCorp",
      location: "Ho Chi Minh City",
      salary: "$3000",
      type: "Remote",
      typeColor: "bg-blue-500",
      posted: "2 days ago",
      logo: "https://static.vecteezy.com/system/resources/previews/008/214/517/non_2x/abstract-geometric-logo-or-infinity-line-logo-for-your-company-free-vector.jpg",
    },
    {
      id: 3,
      title: "UX Designer",
      company: "DesignStudio",
      location: "Hanoi",
      salary: "$2800",
      type: "Hybrid",
      typeColor: "bg-green-500",
      posted: "3 days ago",
      logo: "https://thewebmax.org/react/jobzilla/assets/images/jobs-company/pic2.jpg",
    },
  ],
};
