export const routes = {
  BASE: "/",
  SIGN_UP: "sign-up",
  SIGN_IN: "sign-in",
  JOB_SEARCH: "job-search",
  JOB_DETAIL: "job-detail",
  VERIFY_EMAIL: "verify-email",
  EMPLOYER_SEARCH: "employer-search",
  EMPLOYER_DETAIL: "employer-detail",
  ARTICLES: "articles",
  ARTICLES_DETAIL: "article-detail",
  SETTINGS: "settings",
  MY_RESUME: "resumes",
  MY_SAVED_JOBS: "saved-jobs",
  MY_APPLIED_JOBS: "applied-jobs",
  MESSAGES: "messages",
  FORGOT_PASSWORD: "forgot-password",
  RESET_PASSWORD: "reset-password",
  CREATE_PASSWORD: "create-password",
};

export const employer_routes = {
  BASE: "/employer",
  SIGN_UP: "sign-up",
  SIGN_IN: "sign-in",
  HOME: "home",
  APPLICATIONS: "applications",
  SEARCH_TALENTS: "search-talents",
  VIEWED_TALENTS: "viewed-talents",
  SAVED_TALENTS: "saved-talents",
  ORGANIZATION: "organization",
  JOBS: "jobs",
  JOB_ADD: "jobs/add",
  SETTINGS: "settings",
  FORGOT_PASSWORD: "forgot-password",
  RESET_PASSWORD: "reset-password",
};
