export const routes = {
  BASE: "/",
  SIGN_UP: "sign-up",
  SIGN_IN: "sign-in",
  JOB_SEARCH: "job-search",
  JOB_DETAIL: "job-detail",
  VERIFY_EMAIL: "verify-email",
  EMPLOYER_SEARCH: "employer-search",
  EMPLOYER_DETAIL: "employer-detail",
  ARTICLES: "articles",
  ARTICLES_DETAIL: "article-detail",
  SETTINGS: "settings",
  MY_RESUME: "resumes",
  MY_SAVED_JOBS: "saved-jobs",
  MY_APPLIED_JOBS: "applied-jobs",
  MESSAGES: "messages",
  FORGOT_PASSWORD: "forgot-password",
  RESET_PASSWORD: "reset-password",
  CREATE_PASSWORD: "create-password",
  CREATE_CV: "cv-builder",
  LINKEDIN_AUTHENTICATE: "linkedin/authenticate",
  NOTIFICATIONS: "notifications",
};

export const employer_routes = {
  BASE: "/employer",
  SIGN_UP: "sign-up",
  SIGN_IN: "sign-in",
  HOME: "home",
  APPLICATIONS: "applications",
  ORGANIZATION: "organization",
  JOBS: "jobs",
  JOB_ADD: "jobs/add",
  JOB_EDIT: "jobs/edit/:id",
  SETTINGS: "settings",
  FORGOT_PASSWORD: "forgot-password",
  RESET_PASSWORD: "reset-password",
  VERIFY_EMAIL: "verify-email",
  NOTIFICATIONS: "notifications",
};

export const admin_routes = {
  BASE: "/admin",
  DASHBOARD: "dashboard",
  USERS: "users",
  EMPLOYERS: "employers",
  POSTS: "posts",
  POST_CATEGORIES: "post-categories",
  JOBS: "jobs",
  SETTINGS: "settings",
  FORGOT_PASSWORD: "forgot-password",
  RESET_PASSWORD: "reset-password",
  VERIFY_EMAIL: "verify-email",
  LOCATION: "location",
  CATEGORY_JOBS_INDUSTRIES: "category-jobs-industries",
};
