export const initialJobCategoryOptions = [
  { id: "102220100", name: "IT - Software" },
  { id: "102220200", name: "IT - Hardware / Networking" },
  { id: "102220300", name: "Interior / Exterior" },
  { id: "102220400", name: "Interpreter / Translator" },
  { id: "102220401", name: "Interpreter / Translator (Japanese)" },
  { id: "102220500", name: "Accounting / Auditing" },
  { id: "102220600", name: "Administration / HR" },
  { id: "102220700", name: "Banking / Finance" },
  { id: "102220800", name: "Education / Training" },
  { id: "102220900", name: "Design / Creative" },
  { id: "102221000", name: "Engineering" },
  { id: "102221100", name: "Customer Service" },
  { id: "102221200", name: "Manufacturing" },
  { id: "102221300", name: "Marketing / PR" },
  { id: "102221400", name: "Medical / Healthcare" },
  { id: "102221500", name: "Sales / Business Development" },
  { id: "102221600", name: "export Construction / Civil Engineering" },
  { id: "102221700", name: "Logistics / Warehouse" },
  { id: "102221800", name: "Hospitality / Tourism" },
  { id: "102221900", name: "Legal / Compliance" },
  { id: "102222000", name: "Others" },
];

export const initialJobPostingOptions = [
  { id: "JP001", name: "Frontend Developer" },
  { id: "JP002", name: "Backend Developer" },
  { id: "JP003", name: "Fullstack Developer" },
];

export const initialExperienceLevelOptions = [
  { id: "exp_under_1", name: "Under 1 year" },
  { id: "exp_1_2", name: "1 - 2 years" },
  { id: "exp_2_5", name: "2 - 5 years" },
  { id: "exp_5_10", name: "5 - 10 years" },
  { id: "exp_over_10", name: "Over 10 years" },
];

export const initialCareerLevelOptions = [
  { id: "level_intern", name: "Intern" },
  { id: "level_fresher", name: "Fresher" },
  { id: "level_staff", name: "Staff" },
  { id: "level_manager", name: "Manager" },
  { id: "level_director", name: "Director" },
];

export const initialPositionTypeOptions = [
  { id: "emp_full_time", name: "Full-time" },
  { id: "emp_part_time", name: "Part-time" },
  { id: "emp_seasonal", name: "Seasonal" },
];

export const initialSalary = { min: 1, max: 10, includeNoSalaryData: false };

export const initialEducationLevelOptions = [
  { id: "edu_junior_high", name: "Junior high school" },
  { id: "edu_high_school", name: "High school" },
  {
    id: "edu_vocational_training",
    name: "Vocational Training/ ITI (Professional Certification)",
  },
  { id: "edu_associate_degree", name: "Associate Degree" },
  { id: "edu_diploma_3yrs", name: "Diploma (3 years)" },
  { id: "edu_bachelor_degree", name: "Bachelor's Degree" },
  { id: "edu_bachelor_engineering", name: "Bachelor of Engineering" },
  { id: "edu_masters_degree", name: "Master's Degree" },
  { id: "edu_master_art", name: "Master of Art (M.A)" },
  { id: "edu_master_commerce", name: "Master of Commerce (M.Com)" },
  { id: "edu_master_science", name: "Master of Science (M.Sc)" },
  { id: "edu_master_architecture", name: "Master of Architecture (M.Arch)" },
  { id: "edu_mba", name: "Master of Business Administration (MBA)" },
  { id: "edu_me_mtech", name: "Master of Engineering/Technology (M.E/M.Tech)" },
  { id: "edu_llm", name: "Master of Law (LLM)" },
  { id: "edu_md_ms", name: "Master of Medicine/Surgery (MD/MS)" },
  { id: "edu_mpharm", name: "Master of Pharmacy (M.Pharm)" },
  { id: "edu_phd", name: "Doctorate (PhD)" },
  { id: "edu_other", name: "Other" },
];

export const schools = [
  {
    region: "Southern Region",
    schools: [
      { id: "1", name: "Tao Tao University" },
      { id: "2", name: "Eastern International University" },
      { id: "3", name: "PetroVietnam University" },
      { id: "4", name: "Mien Tay Construction University" },
      { id: "5", name: "Dong Nai Technology University" },
      { id: "6", name: "Binh Duong Economics and Technology University" },
      { id: "7", name: "Nam Can Tho University" },
      { id: "8", name: "Thu Dau Mot University" },
      { id: "9", name: "Dong Nai University" },
      { id: "10", name: "University of Labor and Social Affairs HCMC" },
      { id: "11", name: "Nguyen Tat Thanh University" },
      { id: "12", name: "HCMC University of Food Industry" },
      {
        id: "13",
        name: "Southern Institute of Civilian and Army Medical Corps",
      },
      {
        id: "14",
        name: "The National Academy of Public Administration - Southern",
      },
      { id: "15", name: "Vietnam Aviation Academy" },
      {
        id: "16",
        name: "Post & Telecommunications Institute and Technology - Southern",
      },
      { id: "17", name: "Pham Ngoc Thach University of Medicine" },
      { id: "18", name: "The University of Medicine and Pharmacy at HCMC" },
      { id: "19", name: "Can Tho University of Medicine and Pharmacy" },
      { id: "20", name: "Vietnamese - German University" },
      { id: "21", name: "HCMC Military College of Arts of Culture" },
      { id: "22", name: "Vo Truong Toan University" },
      { id: "23", name: "Van Hien University" },
      { id: "24", name: "HCMC University of Culture" },
      { id: "25", name: "Tra Vinh University" },
      { id: "26", name: "Tien Giang University" },
      { id: "27", name: "Water Resources University - 2nd" },
      { id: "28", name: "HCMC University of Physical Education and Sports II" },
      { id: "29", name: "Tay Do University" },
      { id: "30", name: "HCMC University of Pedagogy" },
      { id: "31", name: "HCMC University of Physical Education and Sports" },
      { id: "32", name: "HCMC University of Technical Education" },
      { id: "33", name: "Dong Thap University" },
      { id: "34", name: "Saigon University (SGU)" },
      { id: "35", name: "Saigon International University (SIU)" },
      { id: "36", name: "RMIT University Vietnam" },
      {
        id: "37",
        name: "HCMC University - Center for International Education",
      },
      { id: "38", name: "HCMC VNU - Faculty of Economics and Law" },
      { id: "39", name: "HCMC International University" },
      { id: "40", name: "HCMC University of Social Sciences & Humanities" },
      { id: "41", name: "HCMC University of Natural Science" },
      { id: "42", name: "HCMC University of Information Technology" },
      { id: "43", name: "HCMC University of Technology (VNU)" },
      { id: "44", name: "Nong Lam University" },
      { id: "45", name: "Nha Trang University - Can Tho" },
      { id: "46", name: "HCMC Foreign Trade University" },
      { id: "47", name: "Banking University HCMC" },
      { id: "48", name: "HCMC Fine Arts University" },
      { id: "49", name: "HCMC Open University" },
      { id: "50", name: "HCMC University of Law" },
      { id: "51", name: "HCMC University of Economics" },
      { id: "52", name: "University of Economics and Finance (UEF)" },
      { id: "53", name: "Long An University Economy Industry" },
      { id: "54", name: "HCMC University of Architecture" },
      { id: "55", name: "HCMC Hung Vuong University" },
      { id: "56", name: "Hoa Sen University" },
      { id: "57", name: "HCMC University of Transport" },
      { id: "58", name: "Van Lang University" },
      {
        id: "59",
        name: "HCMC University of Foreign Languages - Information Technology (HUFLIT)",
      },
      { id: "60", name: "Lac Hong University" },
      { id: "61", name: "HCMC University of Technology (HUTECH)" },
      { id: "62", name: "Hong Bang International University" },
      { id: "63", name: "Mekong University" },
      { id: "64", name: "HCMC University of Industry (HUI)" },
      { id: "65", name: "Gia Dinh University" },
      { id: "66", name: "Saigon Technology University" },
      { id: "67", name: "The People's Police University" },
      { id: "68", name: "Can Tho University" },
      { id: "69", name: "Binh Duong University" },
      { id: "70", name: "Bac Lieu University" },
      { id: "71", name: "Ba Ria - Vung Tau University" },
      { id: "72", name: "Ton Duc Thang University" },
      { id: "73", name: "University of Finance and Marketing" },
      { id: "74", name: "The People's Security University" },
      { id: "75", name: "An Giang University" },
    ],
  },
  {
    region: "Central Region",
    schools: [
      { id: "1", name: "Mien Trung University of Civil Engineering" },
      { id: "2", name: "Banking Academy of Vietnam - Southern" },
      { id: "3", name: "The Naval Institute" },
      { id: "4", name: "Hue Academy of Music" },
      { id: "5", name: "Vinh University" },
      { id: "6", name: "Da Nang University of Physical Education and Sports" },
      { id: "7", name: "Pacific Ocean University" },
      { id: "8", name: "Tay Nguyen University" },
      { id: "9", name: "Vinh Technical Teachers Training University" },
      { id: "10", name: "Quy Nhon University" },
      { id: "11", name: "Quang Nam University" },
      { id: "12", name: "Quang Binh University" },
      { id: "13", name: "Quang Trung University" },
      { id: "14", name: "Phu Yen University" },
      { id: "15", name: "Pham Van Dong University" },
      { id: "16", name: "Phan Chau Trinh University" },
      { id: "17", name: "Nha Trang University" },
      { id: "18", name: "Da Nang Architecture University" },
      { id: "19", name: "Hue University in Quang Tri" },
      { id: "20", name: "Hue University - Faculty of Physical Education" },
      { id: "21", name: "Hue University - Faculty of Hospitality & Tourism" },
      { id: "22", name: "Hue University of Medicine and Pharmacy" },
      { id: "23", name: "Hue University’s College of Education" },
      { id: "24", name: "Hue University of Agriculture and Forestry" },
      { id: "25", name: "Hue University College of Foreign Languages (HUCFL)" },
      { id: "26", name: "Hue University- Hue College of Arts" },
      { id: "27", name: "Hue College of Economics" },
      { id: "28", name: "Hue University of Science" },
      { id: "29", name: "Hong Duc University" },
      { id: "30", name: "Ha Tinh University" },
      { id: "31", name: "Yersin University" },
      { id: "32", name: "Phu Xuan University" },
      { id: "33", name: "Duy Tan University" },
      { id: "34", name: "University of Da Nang in Kon Tum" },
      {
        id: "35",
        name: "Da Nang University - Faculty of Medicine and Pharmacy",
      },
      { id: "36", name: "Da Nang University of Education" },
      { id: "37", name: "Da Nang College of Foreign Languages" },
      { id: "38", name: "Da Nang University of Economics" },
      { id: "39", name: "Da Nang University of Technology" },
      { id: "40", name: "University of DaLat" },
      { id: "41", name: "Van Xuan University of Technology" },
    ],
  },
  {
    region: "Northern Region",
    schools: [
      { id: "1", name: "Asia University of Arts and Design" },
      { id: "2", name: "University of Transport Technology" },
      { id: "3", name: "Hanoi Industrial Textile Garment University" },
      { id: "4", name: "Viet Nam - Hungary Industrial University" },
      { id: "5", name: "Ha Noi Procuratorate University" },
      { id: "6", name: "Noi Vu University" },
      { id: "7", name: "Phenikaa University" },
      { id: "8", name: "Thanh Do University" },
      { id: "9", name: "Thai Binh University" },
      { id: "10", name: "University of Hai Duong" },
      { id: "11", name: "Bac Giang Agriculture and Forestry University" },
      { id: "12", name: "Sao Do University" },
      { id: "13", name: "Tan Trao University" },
      { id: "14", name: "Tokyo Health Sciences University Vietnam" },
      { id: "15", name: "Thanh Hoa University of Culture, Sports and Tourism" },
      { id: "16", name: "Viet Bac University" },
      { id: "17", name: "Kinh Bac University" },
      { id: "18", name: "Thanh Dong University" },
      { id: "19", name: "Trung Vuong University" },
      { id: "20", name: "Academy of Policy and Development" },
      { id: "21", name: "Viet Tri University of Industry" },
      {
        id: "22",
        name: "University of Science and Technology of Hanoi (USTH)",
      },
      { id: "23", name: "Quang Ninh University of Industry" },
      { id: "24", name: "Ha Noi Open University" },
      { id: "25", name: "Institute of Traditional Medicine and Pharmacy" },
      { id: "26", name: "Academy of Finance" },
      { id: "27", name: "Institute of Civilian and Army Medical corps" },
      { id: "28", name: "National Institute of Education Management (NIEM)" },
      { id: "29", name: "Air Force Institute of Aviation" },
      { id: "30", name: "Diplomatic Academy of Vietnam" },
      { id: "31", name: "Banking Academy of Vietnam" },
      { id: "32", name: "Le Qui Don Technical University" },
      { id: "33", name: "The Academy of Cryptography Techniques" },
      { id: "34", name: "Institute of Military Science" },
      { id: "35", name: "Institute of Logistics" },
      { id: "36", name: "The National Academy of Public Administration" },
      { id: "37", name: "Post & Telecommunications Institute and Technology" },
      { id: "38", name: "Institute of Political Military Affairs" },
      { id: "39", name: "The People’s Police Institute" },
      { id: "40", name: "Institute of Border Guard" },
      { id: "41", name: "Academy of Journalism & Communication" },
      { id: "42", name: "Vietnam National Music Institute" },
      { id: "43", name: "The People’s Security Institute" },
      { id: "44", name: "Thaibinh Medical University" },
      { id: "45", name: "Ha Noi School of Public Health" },
      { id: "46", name: "Hai Phong Medical University" },
      { id: "47", name: "Ha Noi Medical University" },
      { id: "48", name: "University of Civil Engineering" },
      { id: "49", name: "Ha Noi Military College of Arts of Culture" },
      { id: "50", name: "Ha Noi University of Culture" },
      { id: "51", name: "University of Technology & Management" },
      { id: "52", name: "Vietnam Commercial University" },
      { id: "53", name: "Water Resources University" },
      {
        id: "54",
        name: "Bac Ninh University of Physical Education and Sports",
      },
      { id: "55", name: "Thanh Tay University" },
      {
        id: "56",
        name: "Thai Nguyen University - Faculty of Foreign Language",
      },
      { id: "57", name: "Thai Nguyen University - College of Sciences" },
      { id: "58", name: "Thai Nguyen University - College of Informatics" },
      { id: "59", name: "Thai Nguyen University - College of Medicine" },
      { id: "60", name: "Thai Nguyen University of Education" },
      { id: "61", name: "Thai Nguyen University of Agriculture and Forestry" },
      { id: "62", name: "Thai Nguyen University of Technology" },
      {
        id: "63",
        name: "Thai Nguyen University of Economics and Business Administration",
      },
      { id: "64", name: "Tay Bac University" },
      { id: "65", name: "Ha Noi University of Physical Education and Sports" },
      { id: "66", name: "National University of Art Education" },
      { id: "67", name: "Nam Dinh University of Technology Education" },
      { id: "68", name: "Hung Yen University of Technology and Education" },
      { id: "69", name: "Ha Noi Pedagogical University No.2" },
      { id: "70", name: "Ha Noi National University of Education" },
      { id: "71", name: "Ha Noi Academy of Theatre and Cinema" },
      { id: "72", name: "University of Odonto - Stomatology (UOS)" },
      { id: "73", name: "Bac Ha International University" },
      {
        id: "74",
        name: "International School - Vietnamese National University",
      },
      { id: "75", name: "VNU, Hanoi Faculty of Education" },
      { id: "76", name: "Ha Noi University of Law" },
      { id: "77", name: "Ha Noi College of Economics" },
      {
        id: "78",
        name: "Ha Noi University of Languages and International Studies",
      },
      { id: "79", name: "Ha Noi University of Social Sciences & Humanities" },
      { id: "80", name: "Ha Noi University of Natural Science" },
      { id: "81", name: "Ha Noi College of Technology (Coltech)" },
      { id: "82", name: "University of Fire Prevention and Fighting" },
      { id: "83", name: "Ha Noi University of Agriculture (HUA)" },
      { id: "84", name: "Nha Trang University - Bac Ninh" },
      { id: "85", name: "Nguyen Trai University" },
      { id: "86", name: "Foreign Trade University (FTU)" },
      { id: "87", name: "Vietnam University of Fine Arts" },
      { id: "88", name: "University of Industrial Fine Art" },
      { id: "89", name: "Ha Noi University of Mining and Geology" },
      { id: "90", name: "Ha Noi Law University (HLU)" },
      { id: "91", name: "Vietnam Forestry University" },
      { id: "92", name: "University of Labor and Social affairs" },
      { id: "93", name: "University of Economic and Technical Industries" },
      { id: "94", name: "Hoa Binh University" },
      { id: "95", name: "Hoa Lu Ninh Binh University" },
      { id: "96", name: "Hai Phong University (Public)" },
      { id: "97", name: "VietNam Maritime University" },
      { id: "98", name: "Ha Noi University" },
      { id: "99", name: "Ha Hoa Tien University" },
      { id: "100", name: "University of Transport and Communications (UTC)" },
      { id: "101", name: "FPT University" },
      { id: "102", name: "Phuong Dong University" },
      { id: "103", name: "Luong The Vinh University - LTVU" },
      { id: "104", name: "Dong Do University" },
      { id: "105", name: "Electric Power University (EPU)" },
      { id: "106", name: "Dai Nam University" },
      { id: "107", name: "Chu van An University" },
      { id: "108", name: "Hai Duong Medical Technical University" },
      { id: "109", name: "National Economics University" },
      {
        id: "110",
        name: "Ha Noi University of Business and Technology (HUBT)",
      },
      { id: "111", name: "Ha Noi Architectural University" },
      { id: "112", name: "Phu Tho Hung Vuong University" },
      { id: "113", name: "Hai Phong Private University (HPU)" },
      { id: "114", name: "Ha Noi University of Pharmacy" },
      { id: "115", name: "Thang Long University" },
      {
        id: "116",
        name: "Nam Dinh Institute of Information Technology for Business",
      },
      { id: "117", name: "Ha Noi University of Industry (HaUI)" },
      { id: "118", name: "Vietnam Trade Union University" },
      { id: "119", name: "Ha Noi University of Technology" },
    ],
  },
];

export const initialMajorOptions = [
  { id: 1, name: "Advertising/ PR" },
  { id: 2, name: "Agriculture/ Aquaculture/ Forestry" },
  { id: 3, name: "Anthropology" },
  { id: 4, name: "Airline Operation/ Airport Management" },
  { id: 5, name: "Architecture" },
  { id: 6, name: "Arts/ Design/ Creative Multimedia" },
  { id: 7, name: "Biology" },
  { id: 8, name: "Bio Technology" },
  { id: 9, name: "Botany" },
  { id: 10, name: "Business Studies/ Administration/ Management" },
  { id: 11, name: "Ceramics" },
  { id: 12, name: "Chemistry" },
  { id: 13, name: "Computer Science/ Information Technology" },
  { id: 14, name: "Commerce" },
  { id: 15, name: "Construction" },
  { id: 16, name: "Dentistry" },
  { id: 17, name: "Economics" },
  { id: 18, name: "Education/ Teaching/ Training" },
  { id: 19, name: "Energy" },
  { id: 20, name: "Engineering (Aviation/ Aeronautics/ Astronautics)" },
  { id: 21, name: "Engineering (Bioengineering/ Biomedical)" },
  { id: 22, name: "Engineering (Chemical)" },
  { id: 23, name: "Engineering (Civil)" },
  { id: 24, name: "Engineering (Computer/ Telecommunication)" },
  { id: 25, name: "Engineering (Electrical/ Electronic)" },
  { id: 26, name: "Engineering (Environmental/ Health/ Safety)" },
  { id: 27, name: "Engineering (Industrial)" },
  { id: 28, name: "Engineering (Marine)" },
  { id: 29, name: "Engineering (Material Science)" },
  { id: 30, name: "Engineering (Mechanical)" },
  { id: 31, name: "Engineering (Mechatronic/ Electromechanical)" },
  { id: 32, name: "Engineering (Metal Fabrication/ Tool & Die/ Welding)" },
  { id: 33, name: "Engineering (Mining/ Mineral)" },
  { id: 34, name: "Engineering (Others)" },
  { id: 35, name: "Engineering (Petroleum/ Oil/ Gas)" },
  { id: 36, name: "Engineering (Plastics)" },
  { id: 37, name: "Export/ Import" },
  { id: 38, name: "Film" },
  { id: 39, name: "Finance/ Accountancy/ Banking" },
  { id: 40, name: "Food & Beverage Services Management" },
  { id: 41, name: "Food Technology/ Nutrition/ Dietetics" },
  { id: 42, name: "Genetic Medicine" },
  { id: 43, name: "Geographical Science" },
  { id: 44, name: "Geology/ Geophysics" },
  { id: 45, name: "Graphic/ Web Designing" },
  { id: 46, name: "History" },
  { id: 47, name: "Hospitality/ Tourism/ Hotel Management" },
  { id: 48, name: "Human Resource Management" },
  { id: 49, name: "Humanities/ Liberal Arts" },
  { id: 50, name: "Insurance" },
  { id: 51, name: "International Business" },
  { id: 52, name: "Journalism" },
  { id: 53, name: "Languages" },
  { id: 54, name: "Law" },
  { id: 55, name: "Library Management" },
  { id: 56, name: "Linguistics" },
  { id: 57, name: "Logistics/ Transportation" },
  { id: 58, name: "Maritime Studies" },
  { id: 59, name: "Marketing" },
  { id: 60, name: "Mass Communications/ Media" },
  { id: 61, name: "Mathematics" },
  { id: 62, name: "Medical Science" },
  { id: 63, name: "Medicine" },
  { id: 64, name: "Microbiology" },
  { id: 65, name: "Music/ Performing Arts Studies" },
  { id: 66, name: "Nursing" },
  { id: 67, name: "Oceanography" },
  { id: 68, name: "Optometry" },
  { id: 69, name: "Personal Services" },
  { id: 70, name: "Pharmacy/ Pharmacology" },
  { id: 71, name: "Philosophy" },
  { id: 72, name: "Physical Therapy/ Physiotherapy" },
  { id: 73, name: "Physics" },
  { id: 74, name: "Political Science" },
  { id: 75, name: "Property Development/ Real Estate Management" },
  { id: 76, name: "Protective Services & Management" },
  { id: 77, name: "Psychology" },
  { id: 78, name: "Quantity Survey" },
  { id: 79, name: "Radiology" },
  { id: 80, name: "Science & Technology" },
  { id: 81, name: "Secretarial" },
  { id: 82, name: "Social Science/ Sociology" },
  { id: 83, name: "Sports Science & Management" },
  { id: 84, name: "Statistics" },
  { id: 85, name: "Textile/ Fashion Design" },
  { id: 86, name: "Urban Studies/ Town Planning" },
  { id: 87, name: "Veterinary" },
  { id: 88, name: "Zoology" },
  { id: 89, name: "Other" },
];

export const initialLanguageOptions = [
  { id: 1, name: "English" },
  { id: 2, name: "Japanese" },
  { id: 3, name: "Korean" },
  { id: 4, name: "Chinese (Mandarin)" },
  { id: 5, name: "Chinese (Cantonese)" },
  { id: 6, name: "Arabic" },
  { id: 7, name: "Burmeses" },
  { id: 8, name: "Danish" },
  { id: 9, name: "Dutch" },
  { id: 10, name: "Filipino" },
  { id: 11, name: "French" },
  { id: 12, name: "German" },
  { id: 13, name: "Greek" },
  { id: 14, name: "Hebrew" },
  { id: 15, name: "Indonesian" },
  { id: 16, name: "Italian" },
  { id: 17, name: "Javanese" },
  { id: 18, name: "Khmer" },
  { id: 19, name: "Lao" },
  { id: 20, name: "Malay" },
  { id: 32, name: "Vietnamese" },
  { id: 33, name: "Other" },
];

export const initialResumePostedWithinOptions = [
  { id: 1, name: "Last 24 hours" },
  { id: 2, name: "Last 3 days" },
  { id: 3, name: "Last 7 days" },
  { id: 4, name: "Last 14 days" },
  { id: 5, name: "Last 30 days" },
];

export const initialLocationOptions = [
  { id: "1", name: "Ho Chi Minh" },
  { id: "2", name: "Ha Noi" },
  { id: "3", name: "Da Nang" },
  { id: "4", name: "An Giang" },
  { id: "5", name: "Ba Ria - Vung Tau" },
  { id: "6", name: "Bac Kan" },
  { id: "7", name: "Bac Giang" },
  { id: "8", name: "Bac Lieu" },
  { id: "9", name: "Bac Ninh" },
  { id: "10", name: "Ben Tre" },
  { id: "11", name: "Binh Dinh" },
  { id: "12", name: "Binh Duong" },
  { id: "13", name: "Binh Phuoc" },
  { id: "14", name: "Binh Thuan" },
  { id: "15", name: "Ca Mau" },
  { id: "16", name: "Can Tho" },
  { id: "17", name: "Cao Bang" },
  { id: "18", name: "Dak Lak" },
  { id: "19", name: "Dak Nong" },
  { id: "20", name: "Dien Bien" },
  { id: "21", name: "Dong Nai" },
  { id: "22", name: "Dong Thap" },
  { id: "23", name: "Gia Lai" },
  { id: "24", name: "Ha Giang" },
  { id: "25", name: "Ha Nam" },
  { id: "26", name: "Ha Tay" },
  { id: "27", name: "Ha Tinh" },
  { id: "28", name: "Hai Duong" },
  { id: "29", name: "Hai Phong" },
  { id: "30", name: "Hau Giang" },
  { id: "31", name: "Hoa Binh" },
  { id: "32", name: "Hung Yen" },
  { id: "33", name: "Kien Giang" },
  { id: "34", name: "Khanh Hoa" },
  { id: "35", name: "Kon Tum" },
  { id: "36", name: "Lai Chau" },
  { id: "37", name: "Lam Dong" },
  { id: "38", name: "Lang Son" },
  { id: "39", name: "Lao Cai" },
  { id: "40", name: "Long An" },
  { id: "41", name: "Nam Dinh" },
  { id: "42", name: "Nghe An" },
  { id: "43", name: "Ninh Binh" },
  { id: "44", name: "Ninh Thuan" },
  { id: "45", name: "Phu Tho" },
  { id: "46", name: "Phu Yen" },
  { id: "47", name: "Quang Binh" },
  { id: "48", name: "Quang Nam" },
  { id: "49", name: "Quang Ngai" },
  { id: "50", name: "Quang Ninh" },
  { id: "51", name: "Quang Tri" },
  { id: "52", name: "Soc Trang" },
  { id: "53", name: "Son La" },
  { id: "54", name: "Tay Ninh" },
  { id: "55", name: "Thai Binh" },
  { id: "56", name: "Thai Nguyen" },
  { id: "57", name: "Thanh Hoa" },
  { id: "58", name: "Thanh Pho Hue" },
  { id: "59", name: "Tien Giang" },
  { id: "60", name: "Tra Vinh" },
  { id: "61", name: "Tuyen Quang" },
  { id: "62", name: "Vinh Long" },
  { id: "63", name: "Vinh Phuc" },
  { id: "64", name: "Yen Bai" },
  { id: "65", name: "Other" },
];
