import type { TalentType } from "@/components/Talent/Talent";

export const mockTalents: TalentType[] = [
  {
    id: "1",
    name: "John Doe",
    avatar: "https://images.unsplash.com/photo-1547514701-42782101795e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8b3JhbmdlfGVufDB8fDB8fHww",
    title: "Front-end Developer",
    location: "Ha Noi",
    salary: "20,000,000 VND",
    experience: "2 years (Experienced Non-Manager)",
    employer: "ViaSoft Company (SaaS/FinTech)",
    age: 24,
    resumeType: "Attachment",
    postedDays: 1,
    isVerified: true,
  },
  {
    id: "2",
    name: "Jane Smith",
    title: "Nhân viên quản lý nhân sự, nhân viên hành chính văn phòng, nhân viên quản lý kho hàng",
    location: "Chau Thanh District, Cho Gao District, My Tho District - Tien Giang",
    salary: "7,000,000 VND - 10,000,000 VND",
    experience: "14 years (Experienced Non-Manager)",
    employer: "Ủy ban nhân dân phường 6",
    age: 36,
    resumeType: "Standard",
    postedDays: 1,
  },
  {
    id: "3",
    name: "Mike Johnson",
    title: "Điện Tử Viễn Thông",
    location: "Ha Noi Hoa",
    salary: "9,000,000 VND - 12,000,000 VND",
    experience: "11 years (Experienced Non-Manager)",
    employer: "Công Ty May Phú Anh",
    age: 34,
    resumeType: "Attachment",
    postedDays: 1,
  },
  {
    id: "4",
    name: "Sarah Williams",
    title: "AI Engineer",
    avatar: "https://images.unsplash.com/photo-1547514701-42782101795e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8b3JhbmdlfGVufDB8fDB8fHww",
    location: "Ho Chi Minh",
    salary: "15,000,000 VND - 20,000,000 VND",
    experience: "1 year (Experienced Non-Manager)",
    employer: "Orthopedic Media",
    age: 23,
    resumeType: "Attachment",
    postedDays: 1,
  },
  {
    id: "5",
    name: "David Brown",
    title: "SOFTWARE ENGINEER",
    location: "Bac Ninh",
    salary: "700 USD - 1,500 USD",
    experience: "3 years (Experienced Non-Manager)",
    employer: "HAMADEN VIETNAM CO.LTD",
    age: 26,
    resumeType: "Attachment",
    postedDays: 1,
  },
  {
    id: "6",
    name: "Emily Davis",
    title: "Nhân viên",
    avatar:"https://images.unsplash.com/photo-1756572735007-99c2972459af?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDMxfDZzTVZqVExTa2VRfHxlbnwwfHx8fHw%3D",
    location: "Son Tra District, Hai Chau District, Thanh Khe District, Cam Le District - Da Nang",
    salary: "Negotiable",
    experience: "2 years (Experienced Non-Manager)",
    employer: "68Land",
    age: 24,
    resumeType: "Attachment",
    postedDays: 1,
  },
  {
    id: "7",
    name: "Emily Davis",
    title: "Nhân viên",
    location: "Son Tra District, Hai Chau District, Thanh Khe District, Cam Le District - Da Nang",
    salary: "Negotiable",
    experience: "2 years (Experienced Non-Manager)",
    employer: "68Land",
    age: 24,
    resumeType: "Attachment",
    postedDays: 1,
  },
  {
    id: "8",
    name: "Emily Davis",
    title: "Nhân viên",
    location: "Son Tra District, Hai Chau District, Thanh Khe District, Cam Le District - Da Nang",
    salary: "Negotiable",
    experience: "2 years (Experienced Non-Manager)",
    employer: "68Land",
    age: 24,
    resumeType: "Attachment",
    postedDays: 1,
  },
  {
    id: "9",
    name: "Emily Davis",
    title: "Nhân viên",
    location: "Son Tra District, Hai Chau District, Thanh Khe District, Cam Le District - Da Nang",
    salary: "Negotiable",
    experience: "2 years (Experienced Non-Manager)",
    employer: "68Land",
    age: 24,
    resumeType: "Attachment",
    postedDays: 1,
  },
  {
    id: "10",
    name: "Emily Davis",
    title: "Nhân viên",
    location: "Son Tra District, Hai Chau District, Thanh Khe District, Cam Le District - Da Nang",
    salary: "Negotiable",
    experience: "2 years (Experienced Non-Manager)",
    employer: "68Land",
    age: 24,
    resumeType: "Attachment",
    postedDays: 1,
  },
  {
    id: "11",
    name: "Emily Davis",
    title: "Nhân viên",
    location: "Son Tra District, Hai Chau District, Thanh Khe District, Cam Le District - Da Nang",
    salary: "Negotiable",
    experience: "2 years (Experienced Non-Manager)",
    employer: "68Land",
    age: 24,
    resumeType: "Attachment",
    postedDays: 1,
  },
  {
    id: "12",
    name: "Emily Davis",
    title: "Nhân viên",
    location: "Son Tra District, Hai Chau District, Thanh Khe District, Cam Le District - Da Nang",
    salary: "Negotiable",
    experience: "2 years (Experienced Non-Manager)",
    employer: "68Land",
    age: 24,
    resumeType: "Attachment",
    postedDays: 1,
  },
  {
    id: "13",
    name: "Emily Davis",
    title: "Nhân viên",
    location: "Son Tra District, Hai Chau District, Thanh Khe District, Cam Le District - Da Nang",
    salary: "Negotiable",
    experience: "2 years (Experienced Non-Manager)",
    employer: "68Land",
    age: 24,
    resumeType: "Attachment",
    postedDays: 1,
  },
];

export const initialRecentSearches = [
  { id: "1", title: "Senior Frontend Developer (React.Js/Next.Js)", location: "Da Nang" },
  { id: "2", title: "(Untitled) h hhh h i ijjiojjjhjj", location: "Bac Giang" },
  { id: "3", title: "(Chưa có tiêu đề)" },
  { id: "4", title: "(Chưa có tiêu đề)" },
  { id: "5", title: "Frontend Engineer", location: "Da Nang" },
];
