export const mockSavedJobs = [
  {
    id: 1,
    title: "Networking Engineer",
    company: "Công ty KMS Technology",
    location: "Da Nang",
    type: "Remote",
    logo: "https://cdn-new.topcv.vn/unsafe/150x/https://static.topcv.vn/company_logos/cong-ty-tnhh-vodaplay-viet-nam-02d756cd7c64074496ce6f9edfd9912f-67a9a8e78acdb.jpg",
    expireDate: "Feb 2, 2019",
    savedDate: "Feb 1, 2019",
    salary: "$2000 - $3000 / tháng",
    posted: "2 ngày trước",
    applications: "15 ngày",
    description: "Phát triển và duy trì các ứng dụng web responsive sử dụng React.js và Next.js",
    requirements: [
      "Hiệp tác với team thiết kế để chuyển các giao diện UI/UX thành mã hóa",
      "Tối ưu hóa hiệu suất ứng dụng và đảm bảo tính tương thích trên các trình duyệt",
      "Viết code sạch, dễ bảo trì và có cấu trúc tốt",
      "Tham gia review code và hỗ trợ các lập trình viên junior",
    ],
    benefits: {
      offer: [
        "Competitive salary with performance bonuses",
        "Flexible working hours and remote work options",
        "Professional development opportunities",
        "Modern office with latest technology",
      ],
      rights: ["Lương cạnh tranh với thưởng hiệu suất", "Giờ làm việc linh hoạt", "Bảo hiểm sức khỏe đầy đủ", "Môi trường làm việc hiện đại"],
    },
    image:
      "https://media.istockphoto.com/id/1224339625/photo/home-office-setup-with-responsive-devices-showing-coronavirus-info.webp?a=1&s=612x612&w=0&k=20&c=yM3I_IEqd-sVx3SIm_l9yGJkGyjxdS4pRryYka2iFJ8=",
  },
  {
    id: 2,
    title: "Visual Designer",
    company: "Công ty KMS Technology",
    location: "Da Nang",
    type: "OnSite",
    logo: "https://cdn-new.topcv.vn/unsafe/150x/https://static.topcv.vn/company_logos/cong-ty-tnhh-alchemy-technologies-5a461a01920ff3af7ac4428eec9a1124-66a745aef387c.jpg",
    expireDate: "Feb 2, 2019",
    savedDate: "Feb 1, 2019",
    salary: "$1800 - $2500 / tháng",
    posted: "3 ngày trước",
    applications: "20 ngày",
    description: "Create stunning visual designs for web and mobile applications",
    requirements: [
      "Strong portfolio demonstrating design skills",
      "Proficiency in Adobe Creative Suite",
      "Understanding of UX principles",
      "Ability to work in a fast-paced environment",
    ],
    benefits: {
      offer: ["Creative work environment", "Latest design tools", "Team collaboration", "Career growth"],
      rights: ["Competitive salary", "Health insurance", "Paid time off", "Training opportunities"],
    },
    image:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YnVzaW5lc3N8ZW58MHx8MHx8fDA%3D",
  },
  {
    id: 3,
    title: "Product Designer",
    company: "Công ty KMS Technology",
    location: "Da Nang",
    type: "OnSite",
    logo: "https://cdn-new.topcv.vn/unsafe/150x/https://static.topcv.vn/company_logos/hgb875NirP73Whm62eZZ4jO6MES1f1BD_1742374737____07c649883e32507eb90dedf0e8d0aa5e.png",
    expireDate: "Feb 2, 2019",
    savedDate: "Feb 1, 2019",
    salary: "$2200 - $3200 / tháng",
    posted: "1 ngày trước",
    applications: "10 ngày",
    description: "Design innovative products that solve user problems",
    requirements: ["Experience with product design methodologies", "Strong user research skills", "Prototyping expertise", "Collaborative mindset"],
    benefits: {
      offer: ["Innovation-focused culture", "Product ownership", "Cross-functional teams", "Impact-driven work"],
      rights: ["Competitive compensation", "Benefits package", "Work-life balance", "Professional development"],
    },
    image:
      "https://images.unsplash.com/photo-1480944657103-7fed22359e1d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjV8fGJ1c2luZXNzfGVufDB8fDB8fHww",
  },
  {
    id: 4,
    title: "Junior Graphic Designer",
    company: "Công ty KMS Technology",
    location: "Da Nang",
    type: "OnSite",
    logo: "https://cdn-new.topcv.vn/unsafe/150x/https://static.topcv.vn/company_logos/pI8cNCFVPLSby1AX0kR2lKCo95t2lYTw_1753426952____857319be7d2303d2aa398ca93dac53f1.png",
    expireDate: "Feb 2, 2019",
    savedDate: "Feb 1, 2019",
    salary: "$1500 - $2000 / tháng",
    posted: "4 ngày trước",
    applications: "25 ngày",
    description: "Create engaging graphics for various marketing materials",
    requirements: ["Basic design skills", "Knowledge of design software", "Creativity and attention to detail", "Willingness to learn"],
    benefits: {
      offer: ["Mentorship program", "Skill development", "Creative freedom", "Team support"],
      rights: ["Entry-level salary", "Health coverage", "Paid leave", "Training programs"],
    },
    image:
      "https://images.unsplash.com/photo-1462556791646-c201b8241a94?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDd8fGJ1c2luZXNzfGVufDB8fDB8fHww",
  },
  {
    id: 5,
    title: "Front End Developer",
    company: "Công ty KMS Technology",
    location: "Da Nang",
    type: "OnSite",
    logo: "https://cdn-new.topcv.vn/unsafe/150x/https://static.topcv.vn/company_logos/9omGpvW5VnKc9fEeSrpbbJt2wkRFfvk2_1718761726____c94f4b3fa519762cf057b7ac09a428ef.png",
    expireDate: "Feb 2, 2019",
    savedDate: "Feb 1, 2019",
    salary: "$2500 - $3500 / tháng",
    posted: "2 ngày trước",
    applications: "12 ngày",
    description: "Build modern web applications using latest technologies",
    requirements: ["Strong JavaScript/TypeScript skills", "React/Next.js experience", "Responsive design expertise", "Problem-solving abilities"],
    benefits: {
      offer: ["Tech-forward environment", "Latest tools and frameworks", "Code quality focus", "Innovation encouraged"],
      rights: ["Competitive tech salary", "Full benefits", "Remote options", "Career advancement"],
    },
    image:
      "https://images.unsplash.com/photo-1462899006636-339e08d1844e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NjF8fGJ1c2luZXNzfGVufDB8fDB8fHww",
  },
  {
    id: 6,
    title: "Marketing Officer",
    company: "Công ty KMS Technology",
    location: "Nha Trang",
    type: "OnSite",
    logo: "https://cdn-new.topcv.vn/unsafe/150x/https://static.topcv.vn/company_logos/EufEMSUaknRoAUf7tiqDldl5eKED6FNs_1655112746____4515a00c07830e71db4588a103bd3055.png",
    expireDate: "Feb 15, 2019",
    savedDate: "Feb 7, 2019",
    salary: "$1800 - $2800 / tháng",
    posted: "5 ngày trước",
    applications: "18 ngày",
    description: "Develop and execute marketing strategies to drive growth",
    requirements: ["Marketing experience", "Digital marketing skills", "Analytics proficiency", "Creative thinking"],
    benefits: {
      offer: ["Dynamic marketing team", "Campaign ownership", "Data-driven approach", "Growth opportunities"],
      rights: ["Competitive salary", "Performance bonuses", "Health insurance", "Professional development"],
    },
    image:
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTAwfHxidXNpbmVzc3xlbnwwfHwwfHx8MA%3D%3D",
  },
];
