export const candidates = [
  {
    id: 1,
    name: "Minh Quan",
    avatar: "/asian-professional-man.png",
    status: "Interview",
    date: "13 July, 2021",
    position: "Designer",
  },
  {
    id: 2,
    name: "Nguyễn Tấn Hưng",
    avatar: "/asian-man-developer.png",
    status: "Interview",
    date: "13 July, 2021",
    position: "JavaScript Dev",
  },
  {
    id: 3,
    name: "Nguyễn Tấn Hưng",
    avatar: "/asian-woman-developer.png",
    status: "Shortlisted",
    date: "12 July, 2021",
    position: "Golang Dev",
  },
  {
    id: 4,
    name: "Nguyễn Tấn Hưng",
    avatar: "/asian-man-programmer.jpg",
    status: "Declined",
    date: "11 July, 2021",
    position: ".NET Dev",
  },
  {
    id: 5,
    name: "Lý Thành Toàn",
    avatar: "/asian-man-designer.jpg",
    status: "Hired",
    date: "11 July, 2021",
    position: "Graphic Design",
  },
  {
    id: 6,
    name: "Đoàn Hà",
    avatar: "/asian-woman-designer.jpg",
    status: "Interviewed",
    date: "5 July, 2021",
    position: "Designer",
  },
  {
    id: 7,
    name: "Đoàn Hà",
    avatar: "/asian-woman-professional.png",
    status: "Declined",
    date: "5 July, 2021",
    position: "Designer",
  },
  {
    id: 8,
    name: "Đoàn Hà",
    avatar: "/asian-man-designer-blue-shirt.jpg",
    status: "Shortlisted",
    date: "3 July, 2021",
    position: "Designer",
  },
  {
    id: 10,
    name: "Đoàn Hà",
    avatar: "/asian-woman-black-hair.jpg",
    status: "Interviewed",
    date: "1 July, 2021",
    position: "Designer",
  },
  {
    id: 11,
    name: "Đoàn Hà",
    avatar: "/asian-woman-black-hair.jpg",
    status: "Interviewed",
    date: "1 July, 2021",
    position: "Designer",
  },
  {
    id: 9,
    name: "Đoàn Hà",
    avatar: "/asian-woman-black-hair.jpg",
    status: "Interviewed",
    date: "1 July, 2021",
    position: "Designer",
  },
];
